### PR TITLE
fix NMTstartup handling if device is NOT the NMT Master

### PR DESCRIPTION
**Pull request by lukegluke**
OD_NMTStartup (0x1F80 OD) can be optional

issue #149

### CODE REVIEW

**Comment by CANopenNode** [comment]
Can you fix according to #149

**Comment by lukegluke** [comment]
I make one more commit to fix using OD_NMTStartup for slave too, please merge it too

**Comment by CANopenNode** [comment]
I think, It is OK now.
Files CANopen.h(c) are application specific anyway. After Object Dictionary will be renewed, they will be changed too and probably those files will be moved into "example" directory.

**Comment by lukegluke** [comment]
I told about this commit
https://github.com/lukegluke/CANopenNode/commit/8da2e542f2e1bb4f938b967716cc92f1e9e8ecbf

**Pull request merged**
