### PR TITLE
Add k20 driver

### PR DESCRIPTION
**Pull request by c0d3runn3r**
SDO / OD, Heartbeat, HB consumer all tested and working.  PDO not tested.  Beta driver with "Teensyduino" example.

### CODE REVIEW

**Comment by Phase77** [comment]
Thanks for sharing you driver for the K20.  I am starting a CANopen project on nxp K66.  Were you successful in implementing CANopenNode on the K20?  It appears that the flexcan module is very similar between the K20 and K66.

**Comment by matthew-t-watson** [comment]
I recently threw together a driver for the K64F using the latest Kinetis SDK, of which I've attached the driver. It definitely isn't the optimal solution, as I didn't use any hardware message buffer filtering, but it works.

[K64F_FreeRTOS.zip](https://github.com/CANopenNode/CANopenNode/files/1721571/K64F_FreeRTOS.zip)

**Comment by c0d3runn3r** [comment]
Yes we were, it works great. We pushed it but the repo maintainer thought he was changing the way drivers organized. He never approved the pull request, it sounds like he was going to suggest that individual implementations use their own repo or something (?) I assume our code is still hanging out there somewhere where you can get at it… It’s a hardware implementation

**Comment by Phase77** [comment]
Thanks for help! This definitely gives me a head start and ill be sure to post any new drivers for kinetis devices.

**Comment by martinwag** [comment]
Please add your driver to the wiki https://github.com/CANopenNode/CANopenNode/wiki (https://github.com/CANopenNode/CANopenNode/issues/108)

**Comment by CANopenNode** [comment]
Thanks @c0d3runn3r for your contribution. My apology for my long inactivity.

Your implementation seems very interesting. However, we decided to remove ALL hardware specific code from the CANopenNode (main project).

Your implementation is now listed in [CANopenNode/wiki](https://github.com/CANopenNode/CANopenNode/wiki) besides all other implementations. Please feel free to edit the wiki.

You can follow [Note for contributors](https://github.com/CANopenNode/CANopenNode#note-for-contributors) and make your project more up to date with latest version of CANopenNode.

**Comment by 1saeed** [comment]
@c0d3runn3r Thanks for sharing. I'm using Teensy 4.0 and FlexCAN_T4 library to have CAN 2.0 communication bus. How Can I use this over the FlexCAN_T4 library, is there a simpel example?

**Pull request closed without merging**
