### PR TITLE
SRDO update

### PR DESCRIPTION
**Pull request by nicolazande**
Update SRDO module to take into account previous SDO and PDO module updates.

### CODE REVIEW

**Comment by nicolazande** [comment]
Last year I used your library for a project and it was great. However, I had some problems with the SRDO module. I think it was not up to date with the SDO and PDO module updates and, since I had to partially rewrite and test it, I think it could be useful also for others.
Thanks!

**Comment by CANopenNode** [comment]
Thank you for you contribution. You are right, SRDO was not up to date with current CANopenNode. 

I can't merge directly into CANopenNode, because it could quite change the current formatting and so break the git history. Now I don't have much time but later I would like to carefully integrate it. For now it is here for anyone interested.

**Comment by nicolazande** [comment]
OK perfect. Maybe I can remove some non-fundamental changes in the CANopen.c/h module so the SRDO related changes are clearer.

**Comment by CANopenNode** [comment]
SRDO update is now on the master branch.

**Pull request closed without merging**
