### PR TITLE
NMT: On startup, set state to operational when master

### PR DESCRIPTION
**Pull request by jdascenzio**
This problem was introduced by 06a0493c787e6232a04d1e24376854d8339f1e80
Since this commit, the master don't start to operational state

### CODE REVIEW

**Comment by CANopenNode** [comment]
NMTstartup (Object 0x1F80) is specified by CiA302-2, which describes quite complex CANopen manager (master), bit0.

In CANopenNode is available only a simple NMT master, where application can start remote nodes, including itself, bit1.

Self start of slave is controlled by bit3.

I don't like to implement bit0 for self-start, as it is not according to standard. I think so.

Maybe self-start can be implemented somewhere in the application, if needed.
In the next version I will probably replace "NMTstartup" argument to CO_NMT_process() function with simple bool value or something.

**Comment by jdascenzio** [comment]
I understand your arguments but for the moment, in this branch, the master always remains in the pre-operational state without, it seems to me, no real solution to switch it to operational mode except by directly setting the variable CO-> NMT-> operatingState. Another solution might be to add a function such as: CO_NMT_setInternalState....

**Comment by CANopenNode** [comment]
Yes those are for now the options.
I don't like to change it in current version, because existing devices may start behave differently.

But for upcoming release with new OD such things will be no problem. I'm thinking about changing NMTstartup to custom argument: a bitfield, which will define startup state on the beginning and will also control state in runtime (automatic enter to operational, if errors are gone). Someone could still use 1F80 object, but in own way.

**Comment by CANopenNode** [comment]
But we can add CO_NMT_setInternalState(), which is just a shortcut to NMT-> operatingState = ...

**Comment by jdascenzio** [comment]
> But we can add CO_NMT_setInternalState(), which is just a shortcut to NMT-> operatingState = ...

I create a PR for that:  #232

**Comment by CANopenNode** [comment]
Thanks

**Comment by martinwag** [comment]
Sorry, just going trough this now. You can set your master application to operational state by calling CO_sendNMTcommand() with your own node ID. So I think we don't need another way to do that.

**Comment by jdascenzio** [comment]
You are quite right! So the commit 09f1083ae661fdbc93731840be10fe45aeb678df is not necessary...

**Comment by CANopenNode** [comment]
CO_sendNMTcommand() also sends a CAN NMT message and it is part of optional NMT master. 
But CO_NMT_setInternalState() just simply changes the state and it is in pair with CO_NMT_getInternalState()

**Comment by CANopenNode** [comment]
I think, it is OK now. CO_NMT_setInternalState() is also available in next release.

**Pull request closed without merging**
