### PR TITLE
change SYNC module to be optional

### PR DESCRIPTION
**Pull request by wilkinsw**
This change will allow CO_NO_SYNC to be zero if the project does not wish to use the sync message.

If CO_NO_SYNC is zero the stack does not need to assign a mailbox to it, which is important if you are using hardware filtering and only have a limited number of mailboxes to work with.  This also means you do not have to define EDS entries 1005-1007.

Changes:
- feature verification no longer asserts on `CO_NO_SYNC == 0`
- `CO_SYNC_t COO_SYNC` is no longer allocated if `CO_NO_SYNC == 0`
- `CO_SYNC_init` will not be called if `CO_NO_SYNC == 0`
- split `CO_process_SYNC_RPDO` into two separate functions.
  - `bool_t CO_process_SYNC`  (returns syncWas)
  - `void CO_process_RPDO` (takes syncWas)
- SYNC is now passed to TPDO on init rather than at every process call.
- Both TPDO and RPDO will now check if SYNC is NULL before dereferencing.

### CODE REVIEW

**Comment by JuPrgn** [comment]
Hi, 

This is a great idea to make SYNC optionnal, thank you !

I cannot find `CO_process_SYNC_RPDO()` can you please check if this is missing ?

**Comment by JuPrgn** [comment]
This is working like a charm (SYNC desactivated).

Please note that these files : 
- example\main.c
- PIC32\main_PIC32.c
- socketCAN\CO_Linux_tasks.c

Are still using : 

`syncWas = CO_process_SYNC_RPDO(CO, ...);`

And could be updated with : 
```
syncWas = CO_process_SYNC(CO, ...);
CO_process_RPDO(CO, syncWas);
```

**Comment by martinwag** [comment]
I've had a short look at this. I think disabling things you don't need is a good idea.

We should also conditionally remove the entry from the "Indexes for CANopenNode message objects" Table in CANopen.c as this defines the amount of hardware buffers you need.

**Comment by JuPrgn** [comment]
Please note `free(CO->SYNC);` is not guarded in `CO_delete()`.

**Comment by wilkinsw** [comment]
I'll fix the conflicts and implement those suggestions!

**Comment by wilkinsw** [comment]
@martinwag in response to your comment, CO_RXCAN_NO_MSGS uses CO_NO_SYNC for its calculation, so I don't think touching that block is strictly necessary. We could conditionally define CO_RXCAN_SYNC, but it is only used by CO_SYNC_init() which won't be called if CO_NO_SYNC is 0.

I'd be happy to make that change, but you've mentioned before that you prefer not to touch things unnecessarily to simplify git blame, so I wanted to double check.

**Comment by wilkinsw** [comment]
Actually, no, you're right, it does push the rest of the indexes down. I'll update that.

**Comment by wilkinsw** [comment]
I took another look at it and the indices are incremented using CO_NO_SYNC, so even though CO_RXCAN_SYNC is defined to 1, the next index just becomes (1 + 0).  I don't think we need to change anything there.

**Comment by martinwag** [comment]
Thanks, I missed that.

**Pull request merged**
