### PR TITLE
Fix bool equality checks

### PR DESCRIPTION
**Pull request by odesenfans**
Removed comparisons of boolean values to `false` and `true`. Evaluating
them is enough.

### CODE REVIEW

**Comment by geoffrey-vl** [comment]
Is that considered to be a bad practice?

**Comment by odesenfans** [comment]
@geoffrey-vl yes it's considered bad practice. Nothing major, but it's definitely redundant.

https://softwareengineering.stackexchange.com/questions/12807/make-a-big-deal-out-of-true/12818

**Comment by martinwag** [comment]
Please have a close look at this again. Either I missed something really basic or you are trying to break half of the stack with things like this:

```
--        if(subIndex == 0U  && exception_1003 == false){
++        if(subIndex == 0U  && exception_1003){
```
:-)

I think the discussion on stackoverflow is long enough, but I prefer to have the explicit ==true / ==false when comparing bools in most cases. I think this is more obvious, especially 
```
(bool==false)
over 
(!bool)
```
But I'm open to changing this.

**Comment by odesenfans** [comment]
Thanks for spotting that, I was not careful enough! I started this to replace this:

```
        if (buffer->CANbaseAddress >= 0) {
            return true;
        }
        else {
            return false;
        }
```

Which can be expressed as a one-liner instead. It's generally accepted good practice that you should not compare things to `false` and `true`, but if it's too much of a nitpick no worries! There is more important stuff to change as well :)

**Comment by geoffrey-vl** [comment]
Like mentioned on SO, its a micro optimization. I personally prefer explicit mentioning of true/false, and so do many others. As demonstrated in the PR: it doesn't actually protect you from making big mistakes 😃 
But when maintaining public code I'd encourage going with public accepted conventions and best practices, so I understand the PR and i have no problem dealing with such code.

**Comment by odesenfans** [comment]
It's not even a micro-optimization, the generated code should not change at all from this PR. And we're not in 1980 anymore either so it's not about file size 😄 

It's more about:
a) letting the compiler perform the evaluation of the variable
b) not relying too much on the actual values of `false` and `true`
c) making the code leaner.

No worries if you prefer to keep the existing way either.

**Comment by geoffrey-vl** [comment]
I meant code-readability optimization, not code optimizations  😄

**Comment by martinwag** [comment]
What's the state of this PR? Have you at least triple-checked that this is OK now :-) .

**Comment by odesenfans** [comment]
Hi @martinwag , this can be merged if someone's interested, otherwise if you prefer to keep the current style you can close it. Up to you!

**Pull request merged**
